language: node_js

node_js:
    - "0.10"
    - "0.11"

branches:
  only:
    - master

sudo: false

services:
    - mongodb

before_install:
    - export NODE_ENV=test
    - mongo hpm-test --eval 'db.addUser("hpm-test", "test");'
    - git config --global url."https://".insteadOf git://

install:
    - npm install
    - bower install
    - cp config/prod.js.dist config/prod.js

cache:
    directories:
        - /home/travis/.npm
        - /home/travis/.cache/bower
        - node_modules
        - bower_components

matrix:
    fast_finish: true

    allow_failures:
        - node_js: "0.11"
