language: node_js

node_js:
    - "0.10"
    - "0.11"

before_install:
    - echo -e "Host github.com\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config

install:
    - npm install
    - bower install

cache:
    - node_modules
    - bower_components

matrix:
    fast_finish: true
