language: node_js

node_js:
    - "0.10"
    - "0.11"

before_install:
    - git config --global url."https://".insteadOf git://

install:
    - npm install
    - bower install

cache:
    - node_modules
    - bower_components

matrix:
    fast_finish: true
