language: node_js

node_js:
    - "0.10"
    - "0.11"

branches:
  only:
    - master

sudo: false

services:
    - mongodb

cache:
    directories:
        - /home/travis/.npm
        - /home/travis/.cache/bower
        - node_modules
        - bower_components

matrix:
    fast_finish: true

    allow_failures:
        - node_js: "0.11"

before_install:
    - export NODE_ENV=test
    - mongo hpm-test --eval 'db.addUser("hpm-test", "test");'

install:
    - npm install
    - bower install
    - gulp compile
    - cp config/prod.js.dist config/prod.js

script:
    - gulp lint:ci
    - gulp karma
    - npm start > /dev/null 2>&1 &
    - gulp protractor
