'use strict';

/**
 * @fileoverview
 * Category metadata.
 */

/**
 * @type {Object}
 */
module.exports = {

    'shortName': 'Category',

    'namespace': 'hpm.Model',

    'autoGeneratedKeyType': 'None',

    'defaultResourceName': 'Categories',

    'dataProperties': [

        {
            'name': '_id',
            'dataType': 'MongoObjectId',
            'isNullable': false,
            'defaultValue': '',
            'isPartOfKey': true,
            'validators': [
                {
                    'name': 'required'
                }
            ]
        },

        {
            'name': 'name',
            'dataType': 'String',
            'maxLength': 50,
            'validators': [
                {
                    'maxLength': 50,
                    'name': 'maxLength'
                }
            ]
        }

    ]

};
