'use strict';

/**
 * @fileoverview
 * Preset structural type.
 */

goog.provide('hpm.breeze.metadata.Preset');

/**
 * @type {Object}
 */
hpm.breeze.metadata.Preset = {

    'shortName': 'Preset',

    'namespace': 'hpm.Model',

    'autoGeneratedKeyType': 'None',

    'defaultResourceName': 'Presets',

    'dataProperties': [

        {
            'name': 'id',
            'dataType': 'MongoObjectId',
            'isNullable': false,
            'defaultValue': '',
            'isPartOfKey': true,
            'validators': [
                {
                    'name': 'required'
                }
            ]
        },

        {
            'name': 'name',
            'dataType': 'String',
            'maxLength': 50,
            'validators': [
                {
                    'maxLength': 50,
                    'name': 'maxLength'
                }
            ]
        }

    ]

};
